force-app/main/default/objects/Maintenance_Part__c/Maintenance_Part__c.object-meta.xml
<CustomObject>
    <label>Maintenance Part</label>
    <nameField>
        <label>Maintenance Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Part__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Request__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Quantity_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Utilized__c</fullName>
    <label>Quantity Utilized</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/Part_Inventory__c.object-meta.xml
<CustomObject>
    <label>Part Inventory</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Inventory__c/fields/Minimum_quantity_reminder__c.field-meta.xml
<CustomField>
    <fullName>Minimum_quantity_reminder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Minimum quantity reminder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Parent_Part__c.field-meta.xml
<CustomField>
    <fullName>Parent_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Part</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Parent Part Inventories</relationshipLabel>
    <relationshipName>Part_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Quantity_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Quantity_In_Stock__c</fullName>
    <label>Quantity In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Registration Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MaintenanceTriggerHandlerTest.cls
@isTest
public with sharing class MaintenanceTriggerHandlerTest {
    public MaintenanceTriggerHandlerTest() {

    }

    @TestSetup
    static void createTestData(){

        Vehicle__c vehicleI20 = new Vehicle__c();
        vehicleI20.Name = 'KL 12 K 1402';
        vehicleI20.Make__c = 'Hyundai';
        insert vehicleI20;

        Maintenance_Request__c maintenanceRequestDoorLockChange = new Maintenance_Request__c();
        maintenanceRequestDoorLockChange.Name = 'Change door lock';
        maintenanceRequestDoorLockChange.Vehicle__c = vehicleI20.Id;
        insert maintenanceRequestDoorLockChange;

        Maintenance_Request__c maintenanceRequestDoorChange = new Maintenance_Request__c();
        maintenanceRequestDoorChange.Name = 'Change door';
        maintenanceRequestDoorChange.Vehicle__c = vehicleI20.Id;
        insert maintenanceRequestDoorChange;

        Part_Inventory__c partDataDoor = new Part_Inventory__c();
        partDataDoor.Name = 'Door';
        partDataDoor.Minimum_quantity_reminder__c = true;
        partDataDoor.Quantity_In_Stock__c = 2;
        insert partDataDoor;

        Part_Inventory__c partDataDoorLock = new Part_Inventory__c();
        partDataDoorLock.Name = 'Door_Lock';
        partDataDoorLock.Minimum_quantity_reminder__c = true;
        partDataDoorLock.Quantity_In_Stock__c = 4;
        partDataDoorLock.Parent_Part__c = partDataDoor.Id;
        insert partDataDoorLock;

    }

   @isTest
    public static void updateInventoryTest() {
        
        Part_Inventory__c partDataDoorLock = [SELECT Id, Name FROM Part_Inventory__c WHERE Name = 'Door_Lock'];
        Maintenance_Request__c maintenanceRequestDoorLockChange = [SELECT Id, Name FROM Maintenance_Request__c WHERE Name = 'Change door lock'];
        
        Maintenance_Part__c maintenancePartDoorLock = new Maintenance_Part__c();
        maintenancePartDoorLock.Name = 'Door Lock';
        maintenancePartDoorLock.Maintenance_Request__c = maintenanceRequestDoorLockChange.Id;
        maintenancePartDoorLock.Part__c = partDataDoorLock.Id;
        maintenancePartDoorLock.Quantity_Utilized__c = 1;
        insert maintenancePartDoorLock;
        
        Maintenance_Part__c maintenancePartObj = [SELECT Id, Quantity_Utilized__c FROM Maintenance_Part__c WHERE Name =: 'Door Lock'];
        
        
        maintenancePartObj.Quantity_Utilized__c = 2;
        update maintenancePartObj;
    }

    @isTest
    public static void fullSetPartOrderTest(){

        Part_Inventory__c partInventoryDoor = [SELECT Id, Name FROM Part_Inventory__c WHERE Name =: 'Door'];
        Maintenance_Request__c maintenanceRequestDoor = [SELECT Id, Name FROM Maintenance_Request__c WHERE Name = 'Change door'];

        Maintenance_Part__c maintenancePartDoor = new Maintenance_Part__c();
        maintenancePartDoor.Name = 'Change Right From door';
        maintenancePartDoor.Maintenance_Request__c = maintenanceRequestDoor.Id;
        maintenancePartDoor.Part__c = partInventoryDoor.Id;
        maintenancePartDoor.Quantity_Utilized__c = 2;
        insert maintenancePartDoor;
        
        delete maintenancePartDoor;

    }

}